services:
  backend:
    build:
      context: ../backend
    container_name: backend
    restart: unless-stopped
    volumes:
      - sqlite_data:/data
      - propriedades_media:/data/propriedades
    environment:
      SPRING_PROFILES_ACTIVE: prod
      CORS_ALLOWED_ORIGINS: "http://imobiliariapremium.com.br"
      APP_MEDIA_BASE_DIR: /data/propriedades
      APP_MEDIA_BASE_URL: /propriedades
    networks:
      - appnet

  frontend:
    build:
      context: ../frontend
      args:
        VITE_BACKEND_URL: /api
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - appnet

volumes:
  sqlite_data:
  propriedades_media:

networks:
  appnet:
